### ISSUE TITLE
Reusing session cookies to scrape NSFW pictures

### ISSUE THREAD

**Issue by terorie** [CorentinB/WallhavenScraper#4]
NSFW image pages require a login to view on WallHaven.
We tried implementing a login using http.CookieJar as well as serializing cookies by hand to no avail.

This is an example of a protected URL.
https://alpha.wallhaven.cc/wallpaper/193

_Note that the actual image file is available! We need the metadata/HTML Page_

All that's needed to view the image is the correct cookie header, consisting of multiple cookies including a session token.
The cookies are set in each server response.

The `-u` and `-p` flags are used for authentication.

The [master branch](https://github.com/CorentinB/WallhavenScraper) uses http.CookieJar for cookies.
The [cookie-test branch](https://github.com/CorentinB/WallhavenScraper/tree/cookie-test) reads the cookies externally and serializes them back together before requests.

If you can get login + viewing NSFW to work on either of the branches, let us know asap and please file a Pull Request or contact https://the-eye.eu

----

This is an urgent issue, as WallHaven will completely switch their site structure making crawling much harder in under 5 hours.

**Any pull requests that bring us closer to fixing this are highly welcome!**

**Comment by nektro** [comment]
I made a gist that grabs directly from the CDN
<https://gist.github.com/nektro/3a4c25eb66cb0abf24b84c0239acddbb>

Example:
<https://alpha.wallhaven.cc/wallpaper/193>
<https://wallpapers.wallhaven.cc/wallpapers/full/wallhaven-193.jpg>

**Comment by CorentinB** [comment]
> https://gist.github.com/nektro/3a4c25eb66cb0abf24b84c0239acddbb

That's already what we do, the issue isn't that, look at the issue and the code.

**Comment by terorie** [comment]
@nektro Sorry forgot to mention. This is strictly about the HTML page containing the metadata!

**Comment by terorie** [comment]
Cookies from Chrome work, the `--cookie` flag is a workaround: https://github.com/CorentinB/WallhavenScraper/commit/0acc4a8b82610eff4aa951ef67ce6218969aee5f

**Comment by terorie** [comment]
Workaround working ...
